name: Ali-Hassan-343-Lab5

on:
  workflow_dispatch:

jobs:
  emailsender:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download file
        run: wget https://gitlab.com/oyakivchik/logfile/-/raw/main/access.log

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f Lab5/requirements.txt ]; then pip install -r Lab5/requirements.txt; fi
      - name: Parse logfile
        run:
          python Lab5/logs_parser.py access.log

      - name: Send email
        run:
          python Lab5/ip_email.py olexiy.jakivtchik@gmail.com
